Microsoft Windows [Version 10.0.22621.4317]
(c) Microsoft Corporation. All rights reserved.

C:\Users\HP>cd C:\Users\HP\A. Python Journey\Python_day_7

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain example.com
Traceback (most recent call last):
  File "C:\Users\HP\A. Python Journey\Python_day_7\main.py", line 1, in <module>
    from scanner import ping
ModuleNotFoundError: No module named 'scanner'

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain example.com
Traceback (most recent call last):
  File "C:\Users\HP\A. Python Journey\Python_day_7\main.py", line 2, in <module>
    from logger import log_result, log_error
ImportError: cannot import name 'log_result' from 'logger' (C:\Users\HP\A. Python Journey\Python_day_7\logger.py). Did you mean: 'new_log_result'?

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain example.com
Traceback (most recent call last):
  File "C:\Users\HP\A. Python Journey\Python_day_7\main.py", line 2, in <module>
    from logger import new_log_result, new_log_error
ImportError: cannot import name 'new_log_error' from 'logger' (C:\Users\HP\A. Python Journey\Python_day_7\logger.py). Did you mean: 'new_log_result'?

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain example.com
Traceback (most recent call last):
  File "C:\Users\HP\A. Python Journey\Python_day_7\main.py", line 3, in <module>
    parser=argparse.ArgumentParser(description="\U0001F4E1 ReconBot CLI Scanner")
           ^^^^^^^^
NameError: name 'argparse' is not defined. Did you forget to import 'argparse'?

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain example.com
usage: main.py [-h] [---domain DOMAIN] [--log LOG]
               [--mode {safe,aggressive}]
main.py: error: unrecognized arguments: --domain example.com

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain example.com
üì° example.com -> 23.192.228.80

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain github.com
üì° github.com -> 20.207.73.82

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain github.com --log new_error_log.txt
üì° github.com -> 20.207.73.82

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain example.com --log new_error_log.txt
üì° example.com -> 23.192.228.80

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain httpbin.org
üì° httpbin.org -> 3.233.51.125

C:\Users\HP\A. Python Journey\Python_day_7>python main.py --domain invalid.domain123
üì° ‚ùå Could not resolve invalid.domain123.